/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.sp.notafiscalmvc.view;

import br.senac.sp.notafiscalmvc.controller.NotaFiscalController;
import br.senac.sp.notafiscalmvc.controller.NotaFiscalTable; // importei a tabela

/**
 *
 * @author Raphaela
 */
public class NotaFiscalForm extends javax.swing.JFrame {

    /**
     * Creates new form notaFiscalForm
     */
    public NotaFiscalController controller;
    public NotaFiscalTable tableController;

    public NotaFiscalForm() {
        initComponents();

        controller = new NotaFiscalController();
        tableController = new NotaFiscalTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JTabela1 = new javax.swing.JTabbedPane();
        jAbaListadeNotas = new javax.swing.JPanel();
        jTextoDescricao = new javax.swing.JTextField();
        jTextoValorDaNota = new javax.swing.JTextField();
        jBotaoSalvar = new javax.swing.JButton();
        jLabelNumNota = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextoNumeroDaNota = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoDescricaoActionPerformed(evt);
            }
        });

        jBotaoSalvar.setText("Salvar");
        jBotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSalvarActionPerformed(evt);
            }
        });

        jLabelNumNota.setText("Num nota:");

        jLabelValor.setText("Valor:");

        jLabel1.setText("Nome do prod.:");

        jTextoNumeroDaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoNumeroDaNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAbaListadeNotasLayout = new javax.swing.GroupLayout(jAbaListadeNotas);
        jAbaListadeNotas.setLayout(jAbaListadeNotasLayout);
        jAbaListadeNotasLayout.setHorizontalGroup(
            jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaListadeNotasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBotaoSalvar)
                    .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jAbaListadeNotasLayout.createSequentialGroup()
                            .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabelValor))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextoValorDaNota, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(jTextoDescricao)))
                        .addGroup(jAbaListadeNotasLayout.createSequentialGroup()
                            .addComponent(jLabelNumNota)
                            .addGap(29, 29, 29)
                            .addComponent(jTextoNumeroDaNota))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jAbaListadeNotasLayout.setVerticalGroup(
            jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAbaListadeNotasLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumNota)
                    .addComponent(jTextoNumeroDaNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAbaListadeNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextoValorDaNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jBotaoSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabela1.addTab("Registrar nota", jAbaListadeNotas);

        jTable1.setModel(new NotaFiscalTable());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        JTabela1.addTab("Lista de notas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabela1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabela1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSalvarActionPerformed
        // Imprimir dados em tela
        System.out.println("Número da Nota: " + jTextoNumeroDaNota.getText());
        System.out.println("Descrição do Produto: " + jTextoDescricao.getText());
        System.out.println("Valor da Nota: " + jTextoValorDaNota.getText());
        
        // Iniciar variáveis
        int numeroNota;
        double ValorNota;
        String descricaoProduto;
        
        //Converter dados
        numeroNota = Integer.parseInt(jTextoNumeroDaNota.getText());
        descricaoProduto = (jTextoDescricao.getText());
        ValorNota = Double.parseDouble(jTextoValorDaNota.getText());
        controller.salvar(numeroNota, descricaoProduto, ValorNota);
        
        //O refresh serve para limpar dados da tabela
        refreshTable();


    }//GEN-LAST:event_jBotaoSalvarActionPerformed
    // Método que vai limpar os dados
    public void refreshTable() {
        jTable1.invalidate();
        jTable1.repaint();
    }
    private void jTextoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoDescricaoActionPerformed

    private void jTextoNumeroDaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoNumeroDaNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoNumeroDaNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabela1;
    private javax.swing.JPanel jAbaListadeNotas;
    private javax.swing.JButton jBotaoSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNumNota;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextoDescricao;
    private javax.swing.JTextField jTextoNumeroDaNota;
    private javax.swing.JTextField jTextoValorDaNota;
    // End of variables declaration//GEN-END:variables
}
